/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type LocationVolunteer = {
  _type: "locationVolunteer";
  title: string;
  description: string;
  benefits?: Array<string>;
  action: ActionLink;
};

export type LocationInformationBlock = {
  _type: "locationInformationBlock";
  title: string;
  lines?: Array<string>;
};

export type LocationTicketRelease = {
  _type: "locationTicketRelease";
  title: string;
  description: string;
  releaseDate: string;
  action?: ActionLink;
};

export type LocationScheduleSession = {
  _type: "locationScheduleSession";
  category: string;
  startTime: string;
  endTime: string;
};

export type LocationScheduleDay = {
  _type: "locationScheduleDay";
  date: string;
  sessions?: Array<
    {
      _key: string;
    } & LocationScheduleSession
  >;
};

export type LocationFeature = {
  _type: "locationFeature";
  title: string;
  description: string;
  image: ContentImage;
};

export type HowItWorksSection = {
  _type: "howItWorksSection";
  heading: string;
  body: string;
};

export type HowItWorksItem = {
  _type: "howItWorksItem";
  title: string;
  slug: Slug;
  content: string;
  sections?: Array<
    {
      _key: string;
    } & HowItWorksSection
  >;
};

export type HomeStory = {
  _type: "homeStory";
  title: string;
  subtitle: string;
  body: string;
  media: "image" | "scoreboard";
  image?: ContentImage;
};

export type CtaBlock = {
  _type: "ctaBlock";
  heading: string;
  description: string;
  action?: ActionLink;
};

export type HeadlineBlock = {
  _type: "headlineBlock";
  heading: string;
  description: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type VideoHero = {
  _type: "videoHero";
  heading?: string;
  ariaLabel?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  webm?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  mp4?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type ContentImage = {
  _type: "contentImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
};

export type ActionLink = {
  _type: "actionLink";
  label: string;
  href: string;
};

export type Seo = {
  _type: "seo";
  title: string;
  description: string;
};

export type Challenge = {
  _id: string;
  _type: "challenge";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  sortOrder: number;
  image?: ContentImage;
  description: string;
  club: string;
  shot: string;
  distance: string;
  targetHeight?: {
    open: string;
    elite: string;
  };
  timeLimit: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  city: string;
  slug: Slug;
  sortOrder: number;
  dates?: {
    startDate: string;
    endDate: string;
  };
  ctaLabel: string;
  detailStatus: "comingSoon" | "complete";
  venueName?: string;
  introduction?: string;
  hero?: VideoHero;
  primaryAction?: ActionLink;
  features?: Array<
    {
      _key: string;
    } & LocationFeature
  >;
  schedule?: {
    title?: string;
    days?: Array<
      {
        _key: string;
      } & LocationScheduleDay
    >;
  };
  ticketInfo?: {
    title?: string;
    releases?: Array<
      {
        _key: string;
      } & LocationTicketRelease
    >;
  };
  importantInformation?: {
    title?: string;
    blocks?: Array<
      {
        _key: string;
      } & LocationInformationBlock
    >;
    volunteer?: LocationVolunteer;
  };
  seo?: Seo;
};

export type ChallengesPage = {
  _id: string;
  _type: "challengesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  introduction?: string;
  emptyState?: string;
  seo?: Seo;
};

export type LocationsPage = {
  _id: string;
  _type: "locationsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  introduction?: string;
  emptyState?: string;
  seo?: Seo;
};

export type HowItWorksPage = {
  _id: string;
  _type: "howItWorksPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: VideoHero;
  arena?: HeadlineBlock;
  introduction?: string;
  items?: Array<
    {
      _key: string;
    } & HowItWorksItem
  >;
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: VideoHero;
  arena?: HeadlineBlock;
  stories?: Array<
    {
      _key: string;
    } & HomeStory
  >;
  cta?: CtaBlock;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | LocationVolunteer
  | LocationInformationBlock
  | LocationTicketRelease
  | LocationScheduleSession
  | LocationScheduleDay
  | LocationFeature
  | HowItWorksSection
  | HowItWorksItem
  | HomeStory
  | CtaBlock
  | HeadlineBlock
  | SanityImageAssetReference
  | SanityFileAssetReference
  | VideoHero
  | ContentImage
  | ActionLink
  | Seo
  | Challenge
  | Slug
  | Location
  | ChallengesPage
  | LocationsPage
  | HowItWorksPage
  | HomePage
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{    seo{title, description},    hero{      heading,      "posterSrc": poster.asset->url,      "webmSrc": webm.asset->url,      "mp4Src": mp4.asset->url    },    arena{heading, description},    stories[]{      _key,      title,      subtitle,      body,      media,      "image": image{"src": asset->url, alt}    },    cta{      heading,      description,      action{label, href}    }  }
export type HOME_PAGE_QUERY_RESULT =
  | {
      seo: null;
      hero: null;
      arena: null;
      stories: null;
      cta: null;
    }
  | {
      seo: {
        title: string;
        description: string;
      } | null;
      hero: null;
      arena: null;
      stories: null;
      cta: null;
    }
  | {
      seo: {
        title: string;
        description: string;
      } | null;
      hero: {
        heading: string | null;
        posterSrc: string | null;
        webmSrc: string | null;
        mp4Src: string | null;
      } | null;
      arena: null;
      stories: null;
      cta: null;
    }
  | {
      seo: {
        title: string;
        description: string;
      } | null;
      hero: {
        heading: string | null;
        posterSrc: string | null;
        webmSrc: string | null;
        mp4Src: string | null;
      } | null;
      arena: {
        heading: string;
        description: string;
      } | null;
      stories: null;
      cta: null;
    }
  | {
      seo: {
        title: string;
        description: string;
      } | null;
      hero: {
        heading: string | null;
        posterSrc: string | null;
        webmSrc: string | null;
        mp4Src: string | null;
      } | null;
      arena: {
        heading: string;
        description: string;
      } | null;
      stories: Array<{
        _key: string;
        title: string;
        subtitle: string;
        body: string;
        media: "image" | "scoreboard";
        image: {
          src: string | null;
          alt: string;
        } | null;
      }> | null;
      cta: {
        heading: string;
        description: string;
        action: {
          label: string;
          href: string;
        } | null;
      } | null;
    }
  | null;

// Source: sanity/lib/queries.ts
// Variable: HOW_IT_WORKS_PAGE_QUERY
// Query: *[_id == "howItWorksPage"][0]{    seo{title, description},    hero{      heading,      "posterSrc": poster.asset->url,      "webmSrc": webm.asset->url,      "mp4Src": mp4.asset->url    },    arena{heading, description},    introduction,    items[]{      _key,      title,      "slug": slug.current,      content,      sections[]{_key, heading, body}    }  }
export type HOW_IT_WORKS_PAGE_QUERY_RESULT =
  | {
      seo: null;
      hero: null;
      arena: null;
      introduction: null;
      items: null;
    }
  | {
      seo: {
        title: string;
        description: string;
      } | null;
      hero: null;
      arena: null;
      introduction: string | null;
      items: null;
    }
  | {
      seo: {
        title: string;
        description: string;
      } | null;
      hero: {
        heading: string | null;
        posterSrc: string | null;
        webmSrc: string | null;
        mp4Src: string | null;
      } | null;
      arena: null;
      introduction: string | null;
      items: null;
    }
  | {
      seo: {
        title: string;
        description: string;
      } | null;
      hero: {
        heading: string | null;
        posterSrc: string | null;
        webmSrc: string | null;
        mp4Src: string | null;
      } | null;
      arena: {
        heading: string;
        description: string;
      } | null;
      introduction: null;
      items: null;
    }
  | {
      seo: {
        title: string;
        description: string;
      } | null;
      hero: {
        heading: string | null;
        posterSrc: string | null;
        webmSrc: string | null;
        mp4Src: string | null;
      } | null;
      arena: {
        heading: string;
        description: string;
      } | null;
      introduction: string | null;
      items: Array<{
        _key: string;
        title: string;
        slug: string;
        content: string;
        sections: Array<{
          _key: string;
          heading: string;
          body: string;
        }> | null;
      }> | null;
    }
  | null;

// Source: sanity/lib/queries.ts
// Variable: LOCATIONS_PAGE_QUERY
// Query: {    "page": *[_id == "locationsPage"][0]{      title,      introduction,      emptyState,      seo{title, description}    },    "locations": *[_type == "location" && defined(slug.current)]|order(sortOrder asc){      _id,      city,      "slug": slug.current,      dates{startDate, endDate},      ctaLabel    }  }
export type LOCATIONS_PAGE_QUERY_RESULT = {
  page:
    | {
        title: string;
        introduction: null;
        emptyState: null;
        seo: null;
      }
    | {
        title: string | null;
        introduction: null;
        emptyState: null;
        seo: null;
      }
    | {
        title: null;
        introduction: null;
        emptyState: null;
        seo: {
          title: string;
          description: string;
        } | null;
      }
    | {
        title: null;
        introduction: string | null;
        emptyState: null;
        seo: {
          title: string;
          description: string;
        } | null;
      }
    | {
        title: string;
        introduction: string | null;
        emptyState: string | null;
        seo: {
          title: string;
          description: string;
        } | null;
      }
    | null;
  locations: Array<{
    _id: string;
    city: string;
    slug: string;
    dates: {
      startDate: string;
      endDate: string;
    } | null;
    ctaLabel: string;
  }>;
};

// Source: sanity/lib/queries.ts
// Variable: LOCATION_SLUGS_QUERY
// Query: *[_type == "location" && defined(slug.current)]|order(sortOrder asc){    "slug": slug.current  }
export type LOCATION_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: LOCATION_SITEMAP_QUERY
// Query: *[_type == "location" && defined(slug.current)]|order(sortOrder asc){    "slug": slug.current,    _updatedAt  }
export type LOCATION_SITEMAP_QUERY_RESULT = Array<{
  slug: string;
  _updatedAt: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: LOCATION_BY_SLUG_QUERY
// Query: *[_type == "location" && slug.current == $slug][0]{    _id,    city,    "slug": slug.current,    detailStatus,    venueName,    introduction,    ctaLabel,    dates{startDate, endDate},    seo{title, description},    hero{      ariaLabel,      "posterSrc": poster.asset->url,      "webmSrc": webm.asset->url,      "mp4Src": mp4.asset->url    },    primaryAction{label, href},    features[]{      _key,      title,      description,      "image": image{        "src": asset->url,        alt,        "width": asset->metadata.dimensions.width,        "height": asset->metadata.dimensions.height      }    },    schedule{      title,      days[]{        _key,        date,        sessions[]{_key, category, startTime, endTime}      }    },    ticketInfo{      title,      releases[]{        _key,        title,        description,        releaseDate,        action{label, href}      }    },    importantInformation{      title,      blocks[]{_key, title, lines},      volunteer{        title,        description,        benefits,        action{label, href}      }    }  }
export type LOCATION_BY_SLUG_QUERY_RESULT = {
  _id: string;
  city: string;
  slug: string;
  detailStatus: "comingSoon" | "complete";
  venueName: string | null;
  introduction: string | null;
  ctaLabel: string;
  dates: {
    startDate: string;
    endDate: string;
  } | null;
  seo: {
    title: string;
    description: string;
  } | null;
  hero: {
    ariaLabel: string | null;
    posterSrc: string | null;
    webmSrc: string | null;
    mp4Src: string | null;
  } | null;
  primaryAction: {
    label: string;
    href: string;
  } | null;
  features: Array<{
    _key: string;
    title: string;
    description: string;
    image: {
      src: string | null;
      alt: string;
      width: number | null;
      height: number | null;
    };
  }> | null;
  schedule: {
    title: string | null;
    days: Array<{
      _key: string;
      date: string;
      sessions: Array<{
        _key: string;
        category: string;
        startTime: string;
        endTime: string;
      }> | null;
    }> | null;
  } | null;
  ticketInfo: {
    title: string | null;
    releases: Array<{
      _key: string;
      title: string;
      description: string;
      releaseDate: string;
      action: {
        label: string;
        href: string;
      } | null;
    }> | null;
  } | null;
  importantInformation: {
    title: string | null;
    blocks: Array<{
      _key: string;
      title: string;
      lines: Array<string> | null;
    }> | null;
    volunteer: {
      title: string;
      description: string;
      benefits: Array<string> | null;
      action: {
        label: string;
        href: string;
      };
    } | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: CHALLENGES_PAGE_QUERY
// Query: {    "page": *[_id == "challengesPage"][0]{      title,      introduction,      emptyState,      seo{title, description}    },    "challenges": *[_type == "challenge" && defined(slug.current)]|order(sortOrder asc){      _id,      "slug": slug.current,      sortOrder,      title,      club,      shot,      distance,      targetHeight{open, elite},      timeLimit,      description,      "image": image{"src": asset->url, alt}    }  }
export type CHALLENGES_PAGE_QUERY_RESULT = {
  page:
    | {
        title: string;
        introduction: null;
        emptyState: null;
        seo: null;
      }
    | {
        title: string | null;
        introduction: null;
        emptyState: null;
        seo: null;
      }
    | {
        title: null;
        introduction: null;
        emptyState: null;
        seo: {
          title: string;
          description: string;
        } | null;
      }
    | {
        title: null;
        introduction: string | null;
        emptyState: null;
        seo: {
          title: string;
          description: string;
        } | null;
      }
    | {
        title: string;
        introduction: string | null;
        emptyState: string | null;
        seo: {
          title: string;
          description: string;
        } | null;
      }
    | null;
  challenges: Array<{
    _id: string;
    slug: string;
    sortOrder: number;
    title: string;
    club: string;
    shot: string;
    distance: string;
    targetHeight: {
      open: string;
      elite: string;
    } | null;
    timeLimit: string;
    description: string;
    image: {
      src: string | null;
      alt: string;
    } | null;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "homePage"][0]{\n    seo{title, description},\n    hero{\n      heading,\n      "posterSrc": poster.asset->url,\n      "webmSrc": webm.asset->url,\n      "mp4Src": mp4.asset->url\n    },\n    arena{heading, description},\n    stories[]{\n      _key,\n      title,\n      subtitle,\n      body,\n      media,\n      "image": image{"src": asset->url, alt}\n    },\n    cta{\n      heading,\n      description,\n      action{label, href}\n    }\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_id == "howItWorksPage"][0]{\n    seo{title, description},\n    hero{\n      heading,\n      "posterSrc": poster.asset->url,\n      "webmSrc": webm.asset->url,\n      "mp4Src": mp4.asset->url\n    },\n    arena{heading, description},\n    introduction,\n    items[]{\n      _key,\n      title,\n      "slug": slug.current,\n      content,\n      sections[]{_key, heading, body}\n    }\n  }\n': HOW_IT_WORKS_PAGE_QUERY_RESULT;
    '\n  {\n    "page": *[_id == "locationsPage"][0]{\n      title,\n      introduction,\n      emptyState,\n      seo{title, description}\n    },\n    "locations": *[_type == "location" && defined(slug.current)]|order(sortOrder asc){\n      _id,\n      city,\n      "slug": slug.current,\n      dates{startDate, endDate},\n      ctaLabel\n    }\n  }\n': LOCATIONS_PAGE_QUERY_RESULT;
    '\n  *[_type == "location" && defined(slug.current)]|order(sortOrder asc){\n    "slug": slug.current\n  }\n': LOCATION_SLUGS_QUERY_RESULT;
    '\n  *[_type == "location" && defined(slug.current)]|order(sortOrder asc){\n    "slug": slug.current,\n    _updatedAt\n  }\n': LOCATION_SITEMAP_QUERY_RESULT;
    '\n  *[_type == "location" && slug.current == $slug][0]{\n    _id,\n    city,\n    "slug": slug.current,\n    detailStatus,\n    venueName,\n    introduction,\n    ctaLabel,\n    dates{startDate, endDate},\n    seo{title, description},\n    hero{\n      ariaLabel,\n      "posterSrc": poster.asset->url,\n      "webmSrc": webm.asset->url,\n      "mp4Src": mp4.asset->url\n    },\n    primaryAction{label, href},\n    features[]{\n      _key,\n      title,\n      description,\n      "image": image{\n        "src": asset->url,\n        alt,\n        "width": asset->metadata.dimensions.width,\n        "height": asset->metadata.dimensions.height\n      }\n    },\n    schedule{\n      title,\n      days[]{\n        _key,\n        date,\n        sessions[]{_key, category, startTime, endTime}\n      }\n    },\n    ticketInfo{\n      title,\n      releases[]{\n        _key,\n        title,\n        description,\n        releaseDate,\n        action{label, href}\n      }\n    },\n    importantInformation{\n      title,\n      blocks[]{_key, title, lines},\n      volunteer{\n        title,\n        description,\n        benefits,\n        action{label, href}\n      }\n    }\n  }\n': LOCATION_BY_SLUG_QUERY_RESULT;
    '\n  {\n    "page": *[_id == "challengesPage"][0]{\n      title,\n      introduction,\n      emptyState,\n      seo{title, description}\n    },\n    "challenges": *[_type == "challenge" && defined(slug.current)]|order(sortOrder asc){\n      _id,\n      "slug": slug.current,\n      sortOrder,\n      title,\n      club,\n      shot,\n      distance,\n      targetHeight{open, elite},\n      timeLimit,\n      description,\n      "image": image{"src": asset->url, alt}\n    }\n  }\n': CHALLENGES_PAGE_QUERY_RESULT;
  }
}
